# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 20:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='wyrazenie')),
                ('translation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Translation')),
                ('explanation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Longer explanation')),
                ('example', models.CharField(blank=True, max_length=500, null=True, verbose_name='Example')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Data dodania')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa grupy')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'EN', b'ENGLISH'), (b'IT', b'ITALIAN'), (b'SP', b'SPANISH'), (b'FR', b'FRENCH')], max_length=50, verbose_name='jezyk')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Language'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expression',
            name='groups',
            field=models.ManyToManyField(to='words.Group'),
        ),
    ]
